---
layout: post
title: "Installing python-ldap in cygwin"
date: 2013-03-25T21:04:00+05:30
tags:
 - Python
---

<div class='post'>
<div dir="ltr" style="text-align: left;" trbidi="on">Installing python-ldap in cygwin took a while for me. When I tried to install with<br /><br /><span style="font-family: &quot;Courier New&quot;,Courier,monospace;">easy_install python-ldap</span><br /><br />I got this error<br /><br /><span style="font-family: &quot;Courier New&quot;,Courier,monospace;">Searching for python-ldap<br />Reading http://pypi.python.org/simple/python-ldap/<br />Reading http://www.python-ldap.org/<br />Best match: python-ldap 2.4.10<br />Downloading http://pypi.python.org/packages/source/p/python-ldap/python-ldap-2.4.10.tar.gz#md5=a15827ca13c90e9101e5e9405c1d83be<br />Processing python-ldap-2.4.10.tar.gz<br />Running python-ldap-2.4.10/setup.py -q bdist_egg --dist-dir /tmp/easy_install-JXhRAd/python-ldap-2.4.10/egg-dist-tmp-1wRZxP<br />defines: HAVE_SASL HAVE_TLS HAVE_LIBLDAP_R<br />extra_compile_args:<br />extra_objects:<br />include_dirs: /opt/openldap-RE24/include /usr/include/sasl /usr/include<br />library_dirs: /opt/openldap-RE24/lib /usr/lib<br />libs: ldap_r<br />file Lib/ldap.py (for module ldap) not found<br />file Lib/ldap/controls.py (for module ldap.controls) not found<br />file Lib/ldap/extop.py (for module ldap.extop) not found<br />file Lib/ldap/schema.py (for module ldap.schema) not found<br />warning: no files found matching 'Makefile'<br />warning: no files found matching 'Modules/LICENSE'<br />file Lib/ldap.py (for module ldap) not found<br />file Lib/ldap/controls.py (for module ldap.controls) not found<br />file Lib/ldap/extop.py (for module ldap.extop) not found<br />file Lib/ldap/schema.py (for module ldap.schema) not found<br />file Lib/ldap.py (for module ldap) not found<br />file Lib/ldap/controls.py (for module ldap.controls) not found<br />file Lib/ldap/extop.py (for module ldap.extop) not found<br />file Lib/ldap/schema.py (for module ldap.schema) not found<br />build/temp.cygwin-1.7.17-i686-2.7/Modules/LDAPObject.o: In function `l_ldap_result4':<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/LDAPObject.c:988: undefined reference to `_ber_bvfree'<br />build/temp.cygwin-1.7.17-i686-2.7/Modules/ldapcontrol.o: In function `encode_rfc3876':<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/ldapcontrol.c:216: undefined reference to `_ber_alloc_t'<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/ldapcontrol.c:227: undefined reference to `_ber_flatten'<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/ldapcontrol.c:237: undefined reference to `_ber_free'<br />build/temp.cygwin-1.7.17-i686-2.7/Modules/ldapcontrol.o: In function `decode_rfc2696':<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/ldapcontrol.c:315: undefined reference to `_ber_init'<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/ldapcontrol.c:320: undefined reference to `_ber_scanf'<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/ldapcontrol.c:330: undefined reference to `_ber_free'<br />build/temp.cygwin-1.7.17-i686-2.7/Modules/ldapcontrol.o: In function `encode_rfc2696':<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/ldapcontrol.c:258: undefined reference to `_ber_alloc_t'<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/ldapcontrol.c:263: undefined reference to `_ber_printf'<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/ldapcontrol.c:272: undefined reference to `_ber_printf'<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/ldapcontrol.c:278: undefined reference to `_ber_printf'<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/ldapcontrol.c:284: undefined reference to `_ber_flatten'<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/ldapcontrol.c:293: undefined reference to `_ber_free'<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/ldapcontrol.c:270: undefined reference to `_ber_printf'<br />build/temp.cygwin-1.7.17-i686-2.7/Modules/message.o: In function `LDAPmessage_to_python':<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/message.c:160: undefined reference to `_ber_free'<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/message.c:199: undefined reference to `_ber_memvfree'<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/message.c:243: undefined reference to `_ber_bvfree'<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/message.c:134: undefined reference to `_ber_free'<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/message.c:237: undefined reference to `_ber_bvfree'<br />build/temp.cygwin-1.7.17-i686-2.7/Modules/options.o: In function `LDAP_set_option':<br />/tmp/easy_install-JXhRAd/python-ldap-2.4.10/Modules/options.c:70: undefined reference to `_ber_pvt_opt_on'<br />collect2: ld returned 1 exit status<br />error: Setup script exited with error: command 'gcc' failed with exit status 1</span><br /><br />Then I just tried to install a version of python-ldap prior to 2.4.10, like this<br /><br /><span style="font-family: &quot;Courier New&quot;,Courier,monospace;">easy_install -N -S /usr/lib/python2.7/site-packages&nbsp; -d /usr/lib/python2.7/site-packages -s /usr/local/bin&nbsp; python-ldap==2.4.3</span> <br /><br />Voila. It worked fine :)</div></div>


